# Generated by Django 3.1.7 on 2021-03-30 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('base_price', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=128)),
                ('risk_gradient', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'unique_together': {('species', 'name')},
            },
        ),
    ]
