# Generated by Django 3.1.7 on 2021-03-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytype',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
